# Pandasのトレーニング♨

## 参考
開発基盤部会 Wiki
- Pandas  
https://dotnetdevelopmentinfrastructure.osscons.jp/index.php?Pandas

## 準備

### インストール

In [15]:
!pip install numpy
!pip install pandas
!pip install openpyxl

Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (1.21.6)
Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2022.1)
Requirement already satisfied: numpy>=1.21.0 in /opt/conda/lib/python3.10/site-packages (from pandas) (1.21.6)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Collecting openpyxl
  Downloading openpyxl-3.0.10-py2.py3-none-any.whl (242 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.1/242.1 kB 3.1 MB/s eta 0:00:00a 0:00:01
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.0.10

### インポート

In [2]:
import numpy as np
import pandas as pd

## Series

### 生成

#### 配列から

In [3]:
pd.Series([3,7,10,13])

0     3
1     7
2    10
3    13
dtype: int64

#### NumPyから
NumPyの配列から

In [4]:
numpy_array = np.array([3,7,10,13])
numpy_array

array([ 3,  7, 10, 13])

In [5]:
pd.Series(numpy_array)

0     3
1     7
2    10
3    13
dtype: int64

### アクセス

In [19]:
x=pd.Series([3,7,10,13])
x

0     3
1     7
2    10
3    13
dtype: int64

#### インデックス

In [20]:
x[1]

7

#### 抽出

##### 5より大きい値を調査。

In [21]:
# npと似たような動作で、boolのseriesで返る
x >= 5

0    False
1     True
2     True
3     True
dtype: bool

In [22]:
# 上記のseriesでインデックスを指定する。
x[x>=5]

1     7
2    10
3    13
dtype: int64

#### 配列
NumPy配列の取り出し

In [23]:
x.values

array([ 3,  7, 10, 13])

## DataFrame

### 生成

#### 辞書型から

In [46]:
df=pd.DataFrame({
    'xxx': ['aaa', 'bbb', 'ccc', 'ddd', 'eee', 'fff'], # 長さ: 6
    'yyy': [20, 34, 50, 12, 62, 22],                   # 長さ: 6
    'zzz': ['AAA', 'BBB', 'CCC', 'DDD', 'EEE', 'FFF']  # 長さ: 6
})
df

   xxx  yyy  zzz
0  aaa   20  AAA
1  bbb   34  BBB
2  ccc   50  CCC
3  ddd   12  DDD
4  eee   62  EEE
5  fff   22  FFF

In [47]:
# ファイル保存
df.to_csv('temp.csv')

#### NumPyから
NumPyの行列（２次配列）から → [NP ⇔ DF型変換](#...)

#### CSVから

##### 事前にCSVファイルを配置しておく。

In [41]:
# df = pd.read_csv('temp.csv')
# df

##### CSVファイルをダウンロードして...

In [66]:
import io
import requests
url = 'https://dotnetdevelopmentinfrastructure.osscons.jp/index.php?plugin=attach&pcmd=open&file=temp.csv&refer=Pandas'
res = requests.get(url)

###### 直接、読み込む。

In [67]:
df = pd.read_csv(io.BytesIO(res.content), encoding='shift-jis', sep=",")
df

   Unnamed: 0  xxx  yyy  zzz
0           0  aaa   20  AAA
1           1  bbb   34  BBB
2           2  ccc   50  CCC
3           3  ddd   12  DDD
4           4  eee   62  EEE
5           5  fff   22  FFF

###### 一旦保存して、読み込む。

In [54]:
with open('temp.csv', 'wb') as saveFile : saveFile.write(res.content)
df = pd.read_csv('temp.csv', encoding='shift-jis', sep=",")
df

   Unnamed: 0  xxx  yyy  zzz
0           0  aaa   20  AAA
1           1  bbb   34  BBB
2           2  ccc   50  CCC
3           3  ddd   12  DDD
4           4  eee   62  EEE
5           5  fff   22  FFF

#### Excelから
事前にopenpyxlのインストールが必要。

##### 事前にExcelファイルを配置しておく。

In [42]:
# df = pd.read_excel('temp.xlsx')
# df

import io
import requests
url = 'https://dotnetdevelopmentinfrastructure.osscons.jp/index.php?plugin=attach&pcmd=open&file=temp.csv&refer=Pandas'
res = requests.get(url)##### Excelファイルをダウンロードして...

In [57]:
import io
import requests
url = 'https://dotnetdevelopmentinfrastructure.osscons.jp/index.php?plugin=attach&pcmd=open&file=temp.xlsx&refer=Pandas'
res = requests.get(url)

###### 直接、読み込む。

In [58]:
df = pd.read_excel(io.BytesIO(res.content))
df

   Unnamed: 0  xxx  yyy  zzz
0           0  aaa   20  AAA
1           1  bbb   34  BBB
2           2  ccc   50  CCC
3           3  ddd   12  DDD
4           4  eee   62  EEE
5           5  fff   22  FFF

###### 一旦保存して、読み込む。

In [60]:
with open('temp.xlsx', 'wb') as saveFile : saveFile.write(requests.get(url).content)
df = pd.read_excel('temp.xlsx')
df

   Unnamed: 0  xxx  yyy  zzz
0           0  aaa   20  AAA
1           1  bbb   34  BBB
2           2  ccc   50  CCC
3           3  ddd   12  DDD
4           4  eee   62  EEE
5           5  fff   22  FFF

### アクセス

#### 先頭・後尾

##### 先頭

###### 先頭５行を出力（既定値

In [70]:
df.head()

   Unnamed: 0  xxx  yyy  zzz
0           0  aaa   20  AAA
1           1  bbb   34  BBB
2           2  ccc   50  CCC
3           3  ddd   12  DDD
4           4  eee   62  EEE

###### 先頭２行を出力（明示

In [71]:
df.head(2)

   Unnamed: 0  xxx  yyy  zzz
0           0  aaa   20  AAA
1           1  bbb   34  BBB

##### 後尾

###### 後尾５行を出力（既定値

In [72]:
df.tail()

   Unnamed: 0  xxx  yyy  zzz
1           1  bbb   34  BBB
2           2  ccc   50  CCC
3           3  ddd   12  DDD
4           4  eee   62  EEE
5           5  fff   22  FFF

###### 先頭２行を出力（明示

In [74]:
df.tail(2)

   Unnamed: 0  xxx  yyy  zzz
4           4  eee   62  EEE
5           5  fff   22  FFF

#### インデックス

##### 行指定
Seriesが返る。

In [82]:
df.iloc[1]

Unnamed: 0      1
xxx           bbb
yyy            34
zzz           BBB
Name: 1, dtype: object

##### 列指定
Seriesが返る。

In [86]:
# NumPyと同様にスライシングが可能
df.iloc[:,1]

0    aaa
1    bbb
2    ccc
3    ddd
4    eee
5    fff
Name: xxx, dtype: object

##### 行列指定

###### 行列番号

In [87]:
df.iloc[1,0]

1

###### 行番号・列名
locは行名、列名が使える（行名は謎いので使ってない）。

In [88]:
df.loc[1,'xxx']

'bbb'

#### 抽出

##### スライシング

###### 行

In [95]:
df.iloc[2:4]

   Unnamed: 0  xxx  yyy  zzz
2           2  ccc   50  CCC
3           3  ddd   12  DDD

###### 列

In [96]:
df.iloc[:,2:4]

   yyy  zzz
0   20  AAA
1   34  BBB
2   50  CCC
3   12  DDD
4   62  EEE
5   22  FFF

##### 配列で行インデックスを指定

In [97]:
df.iloc[[2,3]]

   Unnamed: 0  xxx  yyy  zzz
2           2  ccc   50  CCC
3           3  ddd   12  DDD

##### 比較演算

#### 行列

#### 行指定（≒ 選択）

#### 列指定（≒ 射影）